# Each new term in the Fibonacci sequence is generated by 
# adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence 
# whose values do not exceed four million, 
# find the sum of the even-valued terms.


# take two values
# add them together to get a third value
# take the second value and add it to the third vlaue

def fib(limit):
  x = 1
  y = 2
  z = 0
  total = 0

  while (z<limit): # while the total sequence is below 4m    
    if (y%2==0): #if the current value is even
      print(str(y) +" is even")
      total=total+y # add it to the total 
    z = x+y # set the "counter" to be the sum
    x = y # set the lowest value to be the highest
    y = z # set the highest value to be the sum of the two
  return total

print(fib(4000000))

